### ISSUE TITLE
CRLB can't read .json calibration file

### ISSUE THREAD

**Issue by aaristov** [imodpasteur/ZOLA-3D#4]
> java.lang.NumberFormatException: For input string: "{"
> 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
> 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 	at java.lang.Double.parseDouble(Double.java:538)
> 	at classes.noncudaProcess.DataPhase.loadJSON(DataPhase.java:590)
> 	at classes.noncudaProcess.DataPhase.load(DataPhase.java:234)
> 	at classes.noncudaProcess.DataPhase.<init>(DataPhase.java:119)
> 	at PasteurLocalization.ZOLA.crlb(ZOLA.java:1116)
> 	at PasteurLocalization.ZOLA.run(ZOLA.java:353)
> 	at ij.IJ.runUserPlugIn(IJ.java:222)
> 	at ij.IJ.runPlugIn(IJ.java:186)
> 	at ij.Executer.runCommand(Executer.java:137)
> 	at ij.Executer.run(Executer.java:66)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by benoitbenoit** [comment]
merci... faut que je regarde ca. bon week end.
benoit
Le 22 juin 2018 6:54 PM, "Andrey Aristov" <notifications@github.com> a
écrit :

**Comment by benoitbenoit** [comment]
Thanks, this option is available since version 0.2.0
