### ISSUE TITLE
Zernike Coefficients

### ISSUE THREAD

**Issue by ajkurz** [imodpasteur/ZOLA-3D#5]
I am quite new to the this field of PSF engineering so I come across a lot of questions. One I am stuck with is the following:

when modeling a PSF with >fiji/Zola/additionaltools/BestPSF model optimization then >calibration:PSF modeling and checking the >CRLB you will end up with calibration file that also contains the zernike coefficients as well as the phase values.
Having a closer look then at the control software for the deformable mirror of thorlabs (https://www.thorlabs.com/newgrouppage9.cfm?objectgroup_id=5056&pn=DMP40/M-P01) and comparing the listed zernike coefficients there with a list in the article (https://en.wikipedia.org/wiki/Zernike_polynomials  -- scroll down to the table of zernike polynoms) there is not really a match between the named coefficients! 
I am quite confused about the assignment. Did I miss any explanation in the paper or in the manual?

**Comment by akurz-wue** [comment]
ah perfect! I was looking for that information, thank you very much!
